services:
  app-api:
    image: app-api
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - my_network
  app-react:
    image: app-react
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8081:80"
    networks:
      - my_network
    depends_on:
      - app-api
  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - my_network

volumes:
  portainer_data:

networks:
  my_network:
    driver: bridge
