apiVersion: v1
kind: Service
metadata:
  name: ing-app-react
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: ing-app-react
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ing-app-react
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: ing-app-react
  template:
    metadata:
      labels:
        app: ing-app-react
    spec:
      containers:
        - name: ing-app-react
          image: react-nginx-app:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-conf
              readOnly: true
      volumes:
        - name: nginx-conf
          hostPath:
            path: /path/to/nginx.conf # Replace with the actual path to your nginx.conf file
            type: File
