apiVersion: v1
kind: Service
metadata:
  name: ing-app-api
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ing-app-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ing-app-api
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: ing-app-api
  template:
    metadata:
      labels:
        app: ing-app-api
    spec:
      containers:
        - name: ing-app-api
          image: ing-app-api
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development