apiVersion: v1
kind: Service
metadata:
  name: portainer
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: portainer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: portainer
  template:
    metadata:
      labels:
        app: portainer
    spec:
      containers:
        - name: portainer
          image: portainer/portainer-ce
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /data
              name: portainer-data
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: portainer-data
          emptyDir: {}
